services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wita
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgres/wita
    ports:
      - "5432:5432"
volumes:
  pgdata: